# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Axel SIMONET - Blog
email: contact@axelsimonet.fr
description: >-
  Blog officiel d'Axel SIMONET • Ici seront expliqués ses différentes expériences professionnels
  dans le cadre de sa formation.
baseurl: ""
url: "https://blog.axelsimonet.fr"
linkedin_username: axel-simonet
github_username: Xelzs
header_pages: 
  - title: "A propos"
    url: https://axelsimonet.fr/#home
    target: true
  - title: "Articles"
    url: /
  - title: "Entreprises"
    url: /enterprises
  - title: "Me contacter"
    url: https://axelsimonet.fr/#contact
    target: true

google_analytics: UA-139407954-2

minima:
  date_format: "%d/%m/%Y"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed 
  - jekyll-seo-tag

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/ 
  - vendor/ruby/
  - CNAME